Create navigation to app button
clitch-dev/clitch-landing-page pull request #17
Opened 2021-06-05 10:09 UTC by Yukit02

**implementation details**

- Subject says at All
- Define App url in helper file

2021-06-05 10:21 UTC, hoonsubin requested changes

2021-06-05 10:21 UTC, hoonsubin commented on src/helpers/snsNavigation.ts
> +    const goToClitchApp = () => window.open('https://app.clitch.life', '_blank')
Please use an anchor tag for opening external pages. Adding a function is not scalable.

```html
<a href="https://app.clitch.life" target="_blank" rel="noopener noreferrer"><button>[call to action button element]</button></a>
```

2021-06-05 10:45 UTC, Yukit02 commented on src/helpers/snsNavigation.ts
> +    const goToClitchApp = () => window.open('https://app.clitch.life', '_blank')
I fixed it.
That is OK?

2021-06-05 10:46 UTC, Yukit02 commented on src/helpers/snsNavigation.ts
> +    const goToClitchApp = () => window.open('https://app.clitch.life', '_blank')
I'll change button in CommunitySectionComponent when this modificate ok

2021-06-07 13:26 UTC, hoonsubin commented
I will change the entire development framework. This PR will be merged.

2021-06-07 13:26 UTC, merged