Feat/apply style to footer
clitch-dev/clitch-landing-page pull request #22
Opened 2021-06-12 04:30 UTC by Yukit02

2021-06-12 05:12 UTC, hoonsubin requested changes
These are some changes I recommend making based on the code. I'll run this source later and add more reviews after the changes

2021-06-12 05:12 UTC, hoonsubin commented on src/styles/main.css
> +@layer utilities {
Please add the font to tailwind config file. Try not to modify the css file

2021-06-12 05:12 UTC, hoonsubin commented on src/footer/FooterIconList.tsx
> +                    @apply fill-current w-10 xs:w-8 mr-2;
I don't think there is a point to use xs? Break points should handle anything above md or xl

2021-06-12 05:12 UTC, hoonsubin commented on src/footer/CenteredFooter.tsx
> -      <FooterCopyright />
Please don't remove the copyright message. It's important

2021-06-12 05:12 UTC, hoonsubin commented on tailwind.config.js
> +            '2xl': { min: '1536px' },
Can you add 3xl as well?

2021-06-12 06:28 UTC, Yukit02 commented on tailwind.config.js
> +            '2xl': { min: '1536px' },
I can, but How minimum width?

2021-06-12 06:48 UTC, hoonsubin commented on tailwind.config.js
> +            '2xl': { min: '1536px' },
`1920px` is a good start. Also, please remove the max property. Only add minimum values. You can do something like this:
```
theme: {
    screens: {
      'sm': '640px',
      // => @media (min-width: 640px) { ... }

      'md': '768px',
      // => @media (min-width: 768px) { ... }

      'lg': '1024px',
      // => @media (min-width: 1024px) { ... }

      'xl': '1280px',
      // => @media (min-width: 1280px) { ... }

      '2xl': '1536px',
      // => @media (min-width: 1536px) { ... }
    }
  }
```
I recommend that you read this article to learn about responsive designing https://responsivedesign.is/strategy/page-layout/defining-breakpoints/

2021-06-12 06:50 UTC, hoonsubin commented on src/styles/main.css
> +@layer utilities {
you can add fonts like this https://tailwindcss.com/docs/font-family#customizing

2021-06-12 10:09 UTC, Yukit02 commented
I fixed it.
Please check again.

2021-06-12 15:11 UTC, hoonsubin requested changes

2021-06-12 15:11 UTC, hoonsubin commented on src/navigation/NavbarTwoColumns.tsx
> -  logo: ReactNode;
Why did you remove this? The Navbar prop is showing an error and the logo is not rendering

2021-06-12 15:18 UTC, hoonsubin commented on src/templates/Footer.tsx
>                <a>
Please add the link for the button

2021-06-12 23:55 UTC, Yukit02 commented
I fixed it.
Please check again.

2021-06-13 02:37 UTC, hoonsubin approved these changes
I guess we can make additional improvements in the next PR

2021-06-13 02:37 UTC, merged