Apply style banner section
clitch-dev/clitch-landing-page pull request #25
Opened 2021-06-19 01:43 UTC by Yukit02

### Implementation details

- Subject says it All

2021-06-19 05:01 UTC, hoonsubin requested changes

2021-06-19 05:01 UTC, hoonsubin commented on src/templates/Footer.tsx
> +            <Link href={AppInfo.link.twitter}>
Please remove the `Link` element and use the `<a>` tag for external links

2021-06-19 06:00 UTC, Yukit02 commented on src/templates/Banner.tsx
> +            <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
Plz tell me How to use props with SVG.
And if I use svg in img src can not change color with only special way.

2021-06-19 06:51 UTC, hoonsubin commented on src/templates/Banner.tsx
> +            <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
how about creating it as a separate component that takes the color as one of its props?

2021-06-20 00:53 UTC, Yukit02 commented
I fixed all.
plz check again.

2021-06-20 08:36 UTC, hoonsubin approved these changes
LGTM

2021-06-20 08:36 UTC, merged