Apply style to vertical features section
clitch-dev/clitch-landing-page pull request #26
Opened 2021-06-19 05:42 UTC by Yukit02

2021-06-19 05:47 UTC, hoonsubin requested changes

2021-06-19 05:47 UTC, hoonsubin commented on src/feature/FeatureImageGrid.tsx
> +  imageSrcTight: string;
please don't add two image sources

2021-06-20 01:37 UTC, Yukit02 commented on src/feature/FeatureImageGrid.tsx
> +  imageSrcTight: string;
Is there a problem with this fix?

2021-06-20 01:39 UTC, Yukit02 commented on src/feature/FeatureImageGrid.tsx
> +    </div>
Is there a problem with this fix?

2021-06-20 08:39 UTC, hoonsubin requested changes

2021-06-20 08:39 UTC, hoonsubin commented on src/feature/FeatureImageGrid.tsx
> +        src={`${props.imageSrc}.svg`}
the property argument value should contain the file extension. manually appending `.svg` is not good

2021-06-20 08:39 UTC, hoonsubin commented on src/feature/FeatureImageGrid.tsx
> +      <img src={`${props.imageSrc}-tight.svg`} className="hidden md:block xl:hidden w-full" />
There is not error handling for images that do not end with `-tight.svg`

2021-06-20 08:44 UTC, Yukit02 commented on src/feature/FeatureImageGrid.tsx
> +      <img src={`${props.imageSrc}-tight.svg`} className="hidden md:block xl:hidden w-full" />
Sry I don't know how to fix this.
plz tell me some idea.

2021-06-20 10:02 UTC, hoonsubin commented on src/feature/FeatureImageGrid.tsx
> +      <img src={`${props.imageSrc}-tight.svg`} className="hidden md:block xl:hidden w-full" />
Remove the hard coded `.svg`

2021-06-20 11:13 UTC, Yukit02 commented on src/feature/FeatureImageGrid.tsx
> +      <img src={`${props.imageSrc}-tight.svg`} className="hidden md:block xl:hidden w-full" />
I thought Can not display images when `.svg` removed
We need to toggle with screen size for image.

2021-06-20 12:07 UTC, hoonsubin commented on src/feature/FeatureImageGrid.tsx
> +      <img src={`${props.imageSrc}-tight.svg`} className="hidden md:block xl:hidden w-full" />
You can still use a vector file as a source (pass the full file path as the param). I believe I mentioned about making the svg file as a component (e.g., TwitterIcon.tsx) and change the style from there.
Plus, don't duplicate the same element. Use one element and resize it depending on the break point

2021-06-25 09:23 UTC, merged