feat/create landing page
clitch-dev/clitch-landing-page pull request #4
Opened 2021-05-04 07:06 UTC by Yukit02

**Implementation details**

- Creates each section components.
- Add define colors as variables.
- Defining a class of "<br>" tags that vary with window size.
- Definition a break points and definition each device size class.

## Remark
- Want to change code of SNSbuttons from CommunitySection component.

2021-05-04 07:38 UTC, hoonsubin requested changes
There are a lot of structural changes that I want to suggest, but because the PR is very large, I would like you to first make the page running before we go into the detailed changes (like folder structuring, code structuring, component styling, etc.)

2021-05-04 07:38 UTC, hoonsubin commented on src/views/LandingPage.vue
> +export default defineComponent({
<img width="480" alt="Screen Shot 2021-05-04 at 4 31 47 PM" src="https://user-images.githubusercontent.com/40356749/116972839-9663fe80-acf6-11eb-8432-10a452ef6804.png">

The page will not load because the router will route to the `Content.vue` component, which is removed.
Either change the routing page <https://github.com/clitch-dev/clitch-landing-page/blob/8d630b79d8713b7a44e3cce290a33c269fe3967c/src/router/index.ts#L9> or remove the routing component altogether and add the components directly to the `App.vue` page <https://github.com/clitch-dev/clitch-landing-page/blob/8d630b79d8713b7a44e3cce290a33c269fe3967c/src/App.vue#L18>

2021-05-04 07:44 UTC, Yukit02 commented on src/views/LandingPage.vue
> +export default defineComponent({
sorry, I fix it

2021-05-04 11:56 UTC, Yukit02 commented on src/views/LandingPage.vue
> +export default defineComponent({
I fixed it, plz try again.

2021-05-05 06:40 UTC, hoonsubin requested changes
Please change the overall structure of the pages. After this change, I will request changes to the page sections.

2021-05-05 06:40 UTC, hoonsubin commented on src/router/index.ts
> +import LandingPage from '../views/LandingPage.vue';
Can you remove the router as a whole? The landing page will only have a single page

2021-05-05 06:40 UTC, hoonsubin commented on src/assets/ts/snsNavigation.ts
> +import { reactive } from 'vue'
Please move all helper scripts to `src/helpers/<script>.ts`

2021-05-05 06:40 UTC, hoonsubin commented on src/layouts/FrontPageLayout.vue
> +import Header from '../components/Header.vue';
We only use a single layout. Please remove all layouts and add the base layout directly to the `App.vue` page

2021-05-06 00:19 UTC, Yukit02 commented on src/router/index.ts
> +import LandingPage from '../views/LandingPage.vue';
How to remove?
If this router removed can't not display Web page.
I think I have to write this line even if it was one

2021-05-07 08:32 UTC, hoonsubin commented on src/router/index.ts
> +import LandingPage from '../views/LandingPage.vue';
you can remove the router functionality from here https://github.com/clitch-dev/clitch-landing-page/blob/7d78026aeaf8cc0cb54831f3cbd3912ef944c58b/src/main.ts#L16

2021-05-07 10:23 UTC, hoonsubin approved these changes

2021-05-07 10:23 UTC, merged